# Generated by Django 4.2.2 on 2023-06-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Дата публікації')),
                ('company', models.CharField(max_length=230, verbose_name='Ціна')),
                ('typeOfProposition', models.CharField(max_length=20, verbose_name='Тип пропозиції')),
                ('culture', models.CharField(max_length=20, verbose_name='Культура')),
                ('volume', models.CharField(max_length=20, verbose_name="Об'єм")),
                ('price', models.CharField(max_length=230, verbose_name='Ціна')),
                ('condition', models.CharField(max_length=20, verbose_name='Умови')),
                ('idcheck', models.CharField(blank=True, max_length=230, verbose_name='ID:')),
            ],
        ),
    ]
